//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CREDITO = new HashSet<CREDITO>();
            this.FACTURA = new HashSet<FACTURA>();
            this.FIADOR = new HashSet<FIADOR>();
        }
    
        public int IDCLIENTE { get; set; }
        public Nullable<int> IDTIPOCLIENTE { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string APELLIDOCLIENTE { get; set; }
        public string DUICLIENTE { get; set; }
        public string NITCLIENTE { get; set; }
        public string DIRECCIONCLIENTE { get; set; }
        public string TELEFONOCLIENTE { get; set; }
        public string EMAILCLIENTE { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPOCLIENTE TIPOCLIENTE { get; set; }
        public virtual ICollection<CREDITO> CREDITO { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<FIADOR> FIADOR { get; set; }
    }
}
