//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITO
    {
        public CREDITO()
        {
            this.FIADOR = new HashSet<FIADOR>();
            this.REFERENCIACOMERCIAL = new HashSet<REFERENCIACOMERCIAL>();
            this.REFERENCIAFINANCIERA = new HashSet<REFERENCIAFINANCIERA>();
            this.REFERENCIAPERSONALFAMILIAR = new HashSet<REFERENCIAPERSONALFAMILIAR>();
            this.REGISTROCREDITO = new HashSet<REGISTROCREDITO>();
        }
    
        public long IDCREDITO { get; set; }
        public Nullable<long> IDFACTURA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDESTADOCREDITO { get; set; }
        public Nullable<decimal> MONTOCREDITO { get; set; }
        public Nullable<decimal> PRIMA { get; set; }
        public Nullable<double> TASAINTERES { get; set; }
        public Nullable<int> PLAZO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADOCREDITO ESTADOCREDITO { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual ICollection<FIADOR> FIADOR { get; set; }
        public virtual ICollection<REFERENCIACOMERCIAL> REFERENCIACOMERCIAL { get; set; }
        public virtual ICollection<REFERENCIAFINANCIERA> REFERENCIAFINANCIERA { get; set; }
        public virtual ICollection<REFERENCIAPERSONALFAMILIAR> REFERENCIAPERSONALFAMILIAR { get; set; }
        public virtual ICollection<REGISTROCREDITO> REGISTROCREDITO { get; set; }
    }
}
