//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.FACTURA = new HashSet<FACTURA>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int IDEMPLEADO { get; set; }
        public string NOMBREEMPLEADO { get; set; }
        public string APELLIDOEMPLEADO { get; set; }
        public string DUIEMPLEADO { get; set; }
        public string NITEMPLEADO { get; set; }
        public string DIRECCIONEMPLEADO { get; set; }
        public string TELEFONOEMPLEADO { get; set; }
        public string EMAILEMPLEADO { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
