//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.CREDITO = new HashSet<CREDITO>();
            this.DEVOLUCION = new HashSet<DEVOLUCION>();
            this.FACTURAPRODUCTO = new HashSet<FACTURAPRODUCTO>();
            this.REGALIA = new HashSet<REGALIA>();
            this.PARAMETROS = new HashSet<PARAMETROS>();
        }
    
        public long IDFACTURA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDEMPLEADO { get; set; }
        public Nullable<long> NUMEROFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAFACTURA { get; set; }
        public Nullable<decimal> MONTOFACTURA { get; set; }
        public Nullable<int> TIPOVENTA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<CREDITO> CREDITO { get; set; }
        public virtual ICollection<DEVOLUCION> DEVOLUCION { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<FACTURAPRODUCTO> FACTURAPRODUCTO { get; set; }
        public virtual ICollection<REGALIA> REGALIA { get; set; }
        public virtual ICollection<PARAMETROS> PARAMETROS { get; set; }
    }
}
