//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIADOR
    {
        public int IDFIADOR { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<long> IDCREDITO { get; set; }
        public string NOMBREFIADOR { get; set; }
        public string APELLIDOFIADOR { get; set; }
        public string DUIFIADOR { get; set; }
        public string NITFIADOR { get; set; }
        public string DIRECCIONFIADOR { get; set; }
        public string TELEFONOFIADOR { get; set; }
        public string EMAILFIADOR { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CREDITO CREDITO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
