//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SVYC : DbContext
    {
        public SVYC()
            : base("name=SVYC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AJUSTEPRECIO> AJUSTEPRECIO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CREDITO> CREDITO { get; set; }
        public virtual DbSet<DEVOLUCION> DEVOLUCION { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADOCREDITO> ESTADOCREDITO { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<FACTURAPRODUCTO> FACTURAPRODUCTO { get; set; }
        public virtual DbSet<FIADOR> FIADOR { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<PARAMETROS> PARAMETROS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROMOCION> PROMOCION { get; set; }
        public virtual DbSet<REFERENCIACOMERCIAL> REFERENCIACOMERCIAL { get; set; }
        public virtual DbSet<REFERENCIAFINANCIERA> REFERENCIAFINANCIERA { get; set; }
        public virtual DbSet<REFERENCIAPERSONALFAMILIAR> REFERENCIAPERSONALFAMILIAR { get; set; }
        public virtual DbSet<REGALIA> REGALIA { get; set; }
        public virtual DbSet<REGISTROCREDITO> REGISTROCREDITO { get; set; }
        public virtual DbSet<TIPOCLIENTE> TIPOCLIENTE { get; set; }
        public virtual DbSet<TIPODOCUMENTO> TIPODOCUMENTO { get; set; }
        public virtual DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
