//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETROS
    {
        public PARAMETROS()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int IDPARAMETRO { get; set; }
        public Nullable<int> VALORPARAMETRO { get; set; }
        public Nullable<System.DateTime> FECHAINICIOVIGENCIA { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
