//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.AJUSTEPRECIO = new HashSet<AJUSTEPRECIO>();
            this.DEVOLUCION = new HashSet<DEVOLUCION>();
            this.FACTURAPRODUCTO = new HashSet<FACTURAPRODUCTO>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.REGALIA = new HashSet<REGALIA>();
            this.PROMOCION = new HashSet<PROMOCION>();
        }
    
        public long IDPRODUCTO { get; set; }
        public Nullable<int> IDMARCA { get; set; }
        public string NOMBREPRODUCTO { get; set; }
        public string DESCRIPCIONPRODUCTO { get; set; }
        public string MODELOPRODUCTO { get; set; }
        public Nullable<decimal> COSTOPRODUCTO { get; set; }
        public Nullable<decimal> PRECIOPRODUCTO { get; set; }
    
        public virtual ICollection<AJUSTEPRECIO> AJUSTEPRECIO { get; set; }
        public virtual ICollection<DEVOLUCION> DEVOLUCION { get; set; }
        public virtual ICollection<FACTURAPRODUCTO> FACTURAPRODUCTO { get; set; }
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual ICollection<REGALIA> REGALIA { get; set; }
        public virtual ICollection<PROMOCION> PROMOCION { get; set; }
    }
}
