//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public PROMOCION()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int IDPROMOCION { get; set; }
        public Nullable<int> PORCENTAJEPROMOCION { get; set; }
        public Nullable<System.DateTime> FECHAINICIOPROMOCION { get; set; }
        public Nullable<System.DateTime> FECHAFINPROMOCION { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
