//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIAPERSONALFAMILIAR
    {
        public long IDREFERENCIAPERSONALFAMILIAR { get; set; }
        public Nullable<long> IDCREDITO { get; set; }
        public Nullable<short> TIPOREFERENCIA { get; set; }
        public string NOMBREREFERENCIAPERSONALFAMILIAR { get; set; }
        public string APELLIDOREFERENCIAPERSONALFAMILIAR { get; set; }
        public string DIRECCIONREFERENCIAPERSONALFAMILIAR { get; set; }
        public string TELEFONOREFERENCIAPERSONALFAMILIAR { get; set; }
        public string EMAILREFERENCIAPERSONALFAMILIAR { get; set; }
    
        public virtual CREDITO CREDITO { get; set; }
    }
}
