//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIAFINANCIERA
    {
        public long IDREFERENCIAFINANCIERA { get; set; }
        public Nullable<long> IDCREDITO { get; set; }
        public Nullable<int> IDTIPODOCUMENTO { get; set; }
        public Nullable<decimal> MONTOREFERENCIAFINANCIERA { get; set; }
    
        public virtual CREDITO CREDITO { get; set; }
        public virtual TIPODOCUMENTO TIPODOCUMENTO { get; set; }
    }
}
