//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIACOMERCIAL
    {
        public long IDREFERENCIACOMERCIAL { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<long> IDCREDITO { get; set; }
        public Nullable<decimal> MONTOREFERENCIACOMERCIAL { get; set; }
        public Nullable<int> CANTIDADCUOTAS { get; set; }
        public Nullable<System.DateTime> FECHAINICIOREFERENCIACOMERCIAL { get; set; }
        public Nullable<System.DateTime> FECHACANCELADOREFERENCIACOMERCIAL { get; set; }
    
        public virtual CREDITO CREDITO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
