//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTROCREDITO
    {
        public long IDREGISTROCREDITO { get; set; }
        public Nullable<long> IDCREDITO { get; set; }
        public Nullable<decimal> SALDOCANCELADO { get; set; }
        public Nullable<int> NUMEROCUOTA { get; set; }
        public Nullable<System.DateTime> FECHAREGISTROCREDITO { get; set; }
    
        public virtual CREDITO CREDITO { get; set; }
    }
}
