//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysVYC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOCLIENTE
    {
        public TIPOCLIENTE()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public int IDTIPOCLIENTE { get; set; }
        public string TIPOCLIENTE1 { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
